language: android
android:
  components:
     - tools
     - platform-tools
     - build-tools-25.0.3
     - android-25.2.5
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository
